server:
  port: 8083
  servlet:
    context-path: /productapp

spring:
  application:
    name: product-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/