spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: client-app
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"