server:
  port: 8099
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: weatherservice
          uri: lb://WEATHER-SERVICE
          predicates:
            - Path=/wservice/**
          filters:
            - AuthenticationFilter
        - id: weatherclient
          uri: lb://WEATHER-CLIENT
          predicates:
            - Path=/wclient/**
          filters:
            - AuthenticationFilter
        - id: authserver
          uri: lb://AUTHSERVER-SERVICE
          predicates:
            - Path=/authserver/**