server:
  port: 8085
  servlet:
    context-path: /couponapp
spring:
  application:
    name: coupon-service
  config:
    import: optional:configserver:http://localhost:8888/
  zipkin:
    enabled: true
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
